### ISSUE TITLE
Transmuter v2

### ISSUE THREAD

**Issue by iboss-ptk** [osmosis-labs/transmuter#5]
## Background
At its core, transmuter is theoretically a constant sum AMM: 

$k = p_0 \cdot x + y$ where the price $p_0 = 1$.

That means total pool shares $s = k$ and pool asset withdrawal is restricted by $s_1 = x_1 + y_1$.

But in return, providing $x_1$ or $y_1$ and getting $s_1$ can be viewed as a swap operation.

With that we can repurpose LP shares token as representation of a basket of coins and treat it as swappable asset so that there is no need to handle getting basket of coins representation separately from swap operation.

To ensure minimum level of risk exposure to any side of the underlying assets, the limits to the ratio of the underlying assets must be configurable.

## Roadmap
- [] Treat LP Shares as Swappable Assets
- [] Support for Configurable Limits
- [] Generalized support for >2 assets
